### Adding Fitlio

POST http://localhost:8080/api/fitlio
Content-Type: application/json

{
  "title": "New Fitlio 1",
  "description": "Strengthen your back muscles",
  "timeMinute": 30,
  "timeHour": 1,
  "date": "2024-03-10",
  "calorie": 100,
  "distance": 0,
  "fitType": "POWER"
}

### Getting Fitlio

GET http://localhost:8080/api/fitlio

### Getting Fitlio by ID

GET http://localhost:8080/api/fitlio/1

### Adding a user

POST http://localhost:8080/api/users/addUser
Content-Type: application/json

{
  "name": "Juri",
  "email": "juri@mail.com",
  "password": "qwerty007"
}